# Generated by Django 4.0.4 on 2022-07-11 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario_signup',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=15)),
                ('pnombre', models.CharField(max_length=50)),
                ('appaterno', models.CharField(max_length=50)),
            ],
        ),
    ]
