# Generated by Django 4.0.4 on 2022-06-14 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Foto',
        ),
    ]
